/// Flutter icons MsgIcon
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MsgIcon
///      fonts:
///       - asset: fonts/BookOpen.ttf
///
/// 
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
///
import 'package:flutter/widgets.dart';

class IconBusca {
  IconBusca._();
  static const IconData book_open = const IconData(0xe800, fontFamily: "BookOpen");
  static const IconData book = const IconData(0xe800, fontFamily: "Book");
  static const IconData google = const IconData(0xea88, fontFamily: "Google");
  static const IconData account = const IconData(0xe900, fontFamily: "Account");
  static const IconData wordComplete = const IconData(0xe816, fontFamily: "wordcomplete");
}

